### ISSUE TITLE
Support Auto-Width columns

### ISSUE THREAD

**Issue by mstum** [mstum/Simplexcel#1]
There is an attribute that allows to have Excel automatically size columns.

**Comment by mstum** [comment]
Maybe doing this in 3.0, where I might break a few things for a better API.

**Comment by CodeRevver** [comment]
+1 for this.  Would be good.

**Comment by tipa** [comment]
+1

**Comment by 0xced** [comment]
I have written some kind of prototype using [SixLabors.Fonts](https://github.com/SixLabors/Fonts/) to automatically adjust the columns width here: https://github.com/0xced/Simplexcel/blob/AdjustWidthToContents/src/Simplexcel.TestApp/WorksheetExtensions.cs
