### ISSUE TITLE
Freeze top row

### ISSUE THREAD

**Issue by mguinness** [mstum/Simplexcel#14]
It would be a nice feature if we can freeze top row of worksheet.  It looks like it can be achieved by using the [pane element inside sheetViews](http://openxmldeveloper.org/discussions/formats/f/14/p/1034/2602.aspx).  Any implementation suggestions would be welcome.

**Comment by mguinness** [comment]
I tried the following code inside method CreateSheetFile in class XlsxWriter, but I created an error.  Is it possibly a namespace issue?

```C#
var sheetViews = new XElement(Namespaces.workbook + "sheetViews");
var sheetView = new XElement(Namespaces.workbook + "sheetView");
var pane = new XElement(Namespaces.workbook + "pane",
    new XAttribute("ySplit", 1),
    new XAttribute("topLeftCell", "A2"),
    new XAttribute("activePane", "bottomLeft"),
    new XAttribute("state", "frozen"));
var selection = new XElement(Namespaces.workbook + "selection",
    new XAttribute("pane", "bottomLeft"),
    new XAttribute("activeCell", "A2"),
    new XAttribute("sqref", "A2"));
sheetView.Add(pane);
sheetView.Add(selection);
sheetViews.Add(sheetView);
doc.Root.Add(sheetViews);
```

**Comment by mguinness** [comment]
@mstum Any suggestions as to why this doesn't work.  I'm guessing it may have to do with the position in the XML, but I'm not entirely sure.

**Comment by mstum** [comment]
Heads up, I found the correct syntax and will create a new release that allows freezing soon.

**Comment by mstum** [comment]
Committed a3332397d90bd96d2194ccb457395dea3fc78be3, though still need to test on Excel 2007.

**Comment by mguinness** [comment]
@mstum I guess sheet views needed to be before sheet format?  Anyway, thanks for figuring it out and implementing this feature.

**Comment by mstum** [comment]
I think it's the `workbookViewId` that is required.

**Comment by mstum** [comment]
Pushed to Nuget as 2.0.4.13, along with other changes: https://www.nuget.org/packages/simplexcel/2.0.4.13

**Comment by mguinness** [comment]
Awesome, thanks.  Can confirm that both FreezeTopRow and numeric dates are working as expected.
