### ISSUE TITLE
Support Page Breaks

### ISSUE THREAD

**Issue by jaredrobertsrub** [mstum/Simplexcel#17]
It would be great to be able to support page breaks for print purposes.

Great lightweight lib.

**Comment by mstum** [comment]
Will be available in 2.0.5, sometime this week.

**Comment by mstum** [comment]
Just released 2.0.5 to Nuget, might take an hour or so to show up: https://www.nuget.org/packages/simplexcel/2.0.5.23

Release Notes:
* Add support for manual page breaks. Call `Worksheet.InsertManualPageBreakAfterRow` or `Worksheet.InsertManualPageBreakAfterColumn` with either the zero-based index of the row/column after which to create the break, or with a cell address (e.g., B5) to create the break below or to the left of that cell.
