### ISSUE TITLE
Cell background color

### ISSUE THREAD

**Issue by FarhadKhalafi** [mstum/Simplexcel#21]
Is there anyway to set the interior color of a cell? I need to output a table and really like alternating colors per row to make it easier to read.

**Comment by mstum** [comment]
I've just published [Version 2.2.0.60](https://www.nuget.org/packages/simplexcel/2.2.0.60), which includes support for setting the Cell's fill. Check out the bottom of [USAGE.md](https://github.com/mstum/Simplexcel/blob/master/USAGE.md) for documentation, but to just simply set the background color, set the `Fill.BackgroundColor` property on a cell.

```cs
sheet.Cells["C9"].Fill.BackgroundColor = Color.Navy;
```
