### ISSUE TITLE
Formula support

### ISSUE THREAD

**Issue by Thaledwyn** [mstum/Simplexcel#22]
Formula support would be really nice!

Something like:

Sheet.Cells(1, 1).Formula = "=3+4"
Sheet.Cells(1, 1).Formula = "=SUM(A1:A3)"
Sheet.Cells(1, 1).Formula = "=[B1]+[C4]"

**Comment by mstum** [comment]
That's a good idea!

**Comment by mstum** [comment]
[Version 2.3.0](https://www.nuget.org/packages/simplexcel/) was just released, with formula support. See [the test app](https://github.com/mstum/Simplexcel/blob/0e22dddfcb26b9672ba3ccab6d229da7535127e7/src/Simplexcel.TestApp/Program.cs#L167) for usage examples.
