### ISSUE TITLE
BackColor Bug

### ISSUE THREAD

**Issue by Thaledwyn** [mstum/Simplexcel#23]
I used your Hello World example to play around with the BackColor feature.

When I do the following:

        Dim sheet = New Worksheet("Hello, world!")
        sheet.Cells(0, 0) = "Hello,"
        sheet.Cells("B1") = "World!"
        sheet.Cells(0, 0).Fill.BackgroundColor = Color.Blue
        sheet.Cells("B1").Fill.BackgroundColor = Color.Red
        Dim workbook = New Workbook()
        workbook.Add(sheet)
        workbook.Save(Application.StartupPath & "\test.xlsx")

both cells have a blue backcolor.

When I first create two cells, add format and assign them to the sheet, I get the same behaviour.

What is wrong?
I'm using VS2013 with target framework 4.5.

**Comment by mstum** [comment]
Will check, that code looks good at first glance, but Excel does some weird stuff with the background/foreground colors at times.

**Comment by mstum** [comment]
There was indeed a bug in Simplexcel, [Version 2.2.1.71](https://www.nuget.org/packages/simplexcel/2.2.1.71) should fix that. Thank you for the report!
