### ISSUE TITLE
Make cell index starting from 0,0 or 1,1 an option

### ISSUE THREAD

**Issue by Thaledwyn** [mstum/Simplexcel#24]
For me, it is somehow annoying that Sheet.Cells(0, 0) is the upper left cell instead of Sheet.Cells(1, 1).
Feels counterintuitive.

Maybe you could have some workbook flag where you can decide if you want to start from 0,0 (to ensure compatibility for existing projects) or using 1,1 (like it is also in Excel VBA).

Workbook.ZeroBasedCoords = False/True
or:
Workbook.CellIndexBase = 0 / 1

**Comment by mstum** [comment]
https://github.com/mstum/Simplexcel/issues/43
