### ISSUE TITLE
Signed dlls

### ISSUE THREAD

**Issue by daciantudor** [mstum/Simplexcel#27]
It would be great to have the binaries signed so that they can be used in more restrictive deployments.

**Comment by mstum** [comment]
I'll have a look at this for the 3.0 Release later this year - with delay signing and other tooling improvements, this might actually be no longer such a pain to do.

**Comment by dragomirtitian** [comment]
@mstum What exactly are the pain points?

I created a signed version of it on a branch, and I submitted a PR. We want to use this library in our project, but the we have a hard requirement that all dlls have to be signed.

**Comment by mstum** [comment]
One issue is that the AssemblyVersion shouldn't change anymore, as this would require Binding Redirects, and those are nasty. Also, it's a breaking change, so It'd need a major version bump.

I've got a [v3-dev](https://github.com/mstum/Simplexcel/tree/v3-dev) branch that makes the necessary changes to the build scripts to fix the AssemblyVersion at 3.0.0.0 and offers some convenience functions. I've setup a GitHub Package Repository for dev builds, so you can try out the 3.0.0-v3-dev packages which are signed. They might see in-development functionality added over the next weeks/months, but those won't negatively affect usage. The PublicKey will not change.

Package Version 3.0.0.185-v3-dev is 2.3.0.174 with Strong Naming/Signing: https://github.com/mstum/Simplexcel/packages/48179?version=3.0.0.185-v3-dev

**Comment by mstum** [comment]
Published [3.0.0.181](https://www.nuget.org/packages/simplexcel/3.0.0.181) to nuget, which is signed.
