### ISSUE TITLE
Explicitly Support Dates

### ISSUE THREAD

**Issue by mstum** [mstum/Simplexcel#4]
Allow me to assign a DateTime object to a Date Cell and handle the ISO-8601 and timezone stuff for me. (Note: Using a Text Cell and a proper Excel Format string or ISO8601 format already works)

**Comment by mguinness** [comment]
I looked at source code and see you have XlsxCellTypes class with date member already defined.  What would be required to implement a date member in CellType class?  Any idea on the amount of work required?

**Comment by mstum** [comment]
07971ec26b7d95b05f2c3ff8326334fe95d65ed3
